# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aae0f5c9ff65d450bd442ed93fef913ca5b14fa96c93fbf70b8095d661d3bd8a6ad7745a0934f42fa457312257de06735bff8c1e1638cabf7e1a95cae7c2bd6f

test:
  secret_key_base: 32259631ab9d6d4ce6735806f06134e693655f478fe83b3e9078f5421dfa025ea4f94ddebdd7703f234f9a43c56935963bf4656145b168c31162054015aeb43f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
